### ISSUE TITLE
Request - Viewport rotation

### ISSUE THREAD

**Issue by tomburnett94** [felixvons/Easy-Print-Menu#16]
It really like the simplicity of the viewport generator, my only request would for a rotation function of the viewports for more complex alignments

**Comment by felixvons** [comment]
Hi @tomburnett94 ,

thank you for your feedback :)

Do you have any ideas where I can add the option for the rotation value or intergrate it into the placement workflow?

**Comment by tomburnett94** [comment]
hi @felixvons 
i am not very tech savvy when it comes to programming or coding, but i was using your viewport setups through the 'atlas' function and then creating another field in the shape file called 'rotation' or something, it was then an automatic update field which would pick the first two vertex of the rectangle and then solve for the angle, i was then able to set the viewport by maping the 'map rotation' equal this value. 
This wasn't the exact formula, but i was using something very similar. 

ATAN2($y_at(-1)-$y_at(0),$x_at(-1)-x_at(0))*180/PI()

**Comment by felixvons** [comment]
The rotation feature will be released together with other compatibility updates to the current QGIS LTR 3.34 version
